#!/bin/bash

declare -r PROGNAME=$(basename $0)
HINTDIR=$HOME                       # change this as needed
HINTFILE="hints.txt"                # change this as needed

# case insensitive search by default
sensitive=

# colors enabled by default in ttys
if [ -t 1 ]; then
  colors=1
else
  colors=
fi


function desctext() {
cat <<EOF
${PROGNAME} -- search a hints file

  This program is designed to be a quick reference if you need
  to know something quickly. I use it as a reminder for syntax
  of commands that I use infrequently.

  (If you have grep colorized, your 'hint' output will be too.)

EOF
}   # end of desctext


function usagetext() {
cat <<EOF
Usage:

  ${PROGNAME} [options] SEARCHTERM

  Options:

  -s, --sensitive         Force case sensitive search.
  -i, --insensitive       Force case insensitive search. (default)
  -c, --colors            Force colors. (default)
  -C, --no-colors         Force avoid colors.
  -h, --help              Show help message.

  (Preface SEARCHTERM with a ^ to only search start-of-lines.)
  (Use a capital letter in SEARCHTERM to autoforce case sensitivity.)

EOF
} # end of usagetext


function misctext() {
cat <<EOF
External programs req'd:
  bash, basename, grep (all standard, unless you're on Windows)
Revision History:
  see git log

EOF
}   # end of misctext


function helptext() {
  desctext
  usagetext
  misctext
}


# parse options
while [[ "$1" =~ ^- ]]; do
  case $1 in
    -s | --sensitive )
      sensitive=1
      ;;
    -i | --insensitive )
      sensitive=
      ;;
    -c | --colors )
      colors=1
      ;;
    -C | --no-colors )
      colors=
      ;;
    -h | --help )
      helptext
      exit
      ;;
  esac
  shift
done

# check for empty search
if [[ "" = "$@" ]]; then
  usagetext
  exit 1
fi

# auto-detect case sensitive based on an uppercase letter
if [[ "$@" =~ [A-Z] ]]; then
  sensitive=1
fi

# grep default params
grepopt=

# add case insensitive search
if [ ! $sensitive ]; then
  grepopt="$grepopt --ignore-case"
fi

# add force colors
if [ $colors ]; then
  grepopt="$grepopt --color=always"
else
  grepopt="$grepopt --color=never"
fi



# A blank line:
echo ""

# Finally do the search:
grep -v '^/////' $HINTDIR/$HINTFILE | grep $grepopt "`echo $@`"

if [[ $? -eq 0 ]]; then
  # If we found results, give me a blank line to separate it from the next prompt:
  echo ""
  # A clean exit if a search term was found:
  exit
else
  # Otherwise, exit with error code:
  exit 1
fi


# end of script
